/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-12-19 08:29:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.text.SimpleDateFormat;

public final class authored_005fcontent_005fcorrection_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
request.setCharacterEncoding("utf-8");
      out.write('\n');
      out.write('\n');
      out.write('\n');

String url = "jdbc:mysql://192.168.0.71:3306/recycle";
String user = "recycle";
String password = "1234";


      out.write('\n');
      out.write('\n');
      out.write('	');

	try {
		HttpSession boardSession = request.getSession(false);
		String userUID = (String) session.getAttribute("userUID");

		if (userUID != null) {
			String getUid = request.getParameter("uid");
			int uid = Integer.parseInt(getUid);

			Class.forName("com.mysql.cj.jdbc.Driver");
			Connection conn = DriverManager.getConnection(url, user, password);

			String selectQuery = "SELECT cq.*, ul.user_name " + "FROM contact_question cq "
			+ "INNER JOIN user_list ul ON cq.contact_writer_id = ul.user_uid " + "WHERE uid =?";

			PreparedStatement preparedStatement = conn.prepareStatement(selectQuery);
			preparedStatement.setInt(1, uid);
			ResultSet resultSet = preparedStatement.executeQuery();

			if (resultSet.next()) {
		String requestedUID = resultSet.getString("contact_writer_id");
		if (userUID.equals(requestedUID)) {
			// 여기에 권한이 있는 경우 게시글을 표시하는 코드 추가
			SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
			Timestamp contactDate = resultSet.getTimestamp("contact_reg_date");
			String formatNoticeDate = dateFormat.format(contactDate);
	
      out.write("\n");
      out.write("    \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <title>내가 작성한 글 | 마음을 다시 연결하는 결혼 정보 플랫폼 DASH</title>\n");
      out.write("  <meta charset=\"UTF-8\" />\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("  <meta name=\"keyworeds\" content=\"결혼, wedding, 결혼정보업체, DASH, Re:Connect, 듀오, 가연,\" />\n");
      out.write("  <meta name=\"description\" content=\"안녕하세요, 마음을 다시 연결하는 결혼 정보 플랫폼 DASH 입니다.\" />\n");
      out.write("  <link rel=\"icon\" href=\"../images/favicon.png\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"../CSS/authored_content_correction.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"../CSS/footer_style.css\" />\n");
      out.write("  <link rel=\"stylesheet\" href=\"../CSS/reset.css\" />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("  <!-- 마이페이지헤더 -->\n");
      out.write("  <header class=\"account_header\">\n");
      out.write("    <div class=\"header_btn\">\n");
      out.write("      <div class=\"message_badge\">\n");
      out.write("        <button type=\"button\" class=\"btn_messenger\" onclick=\"\">메신저</button>\n");
      out.write("        <span class=\"push_num\" style=\"display: none\">0</span>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"alarm_badge\">\n");
      out.write("        <button type=\"button\" class=\"btn_alarm\" onclick=\"\">알림</button>\n");
      out.write("        <span class=\"push_num\" style=\"display: none\">0</span>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"member\">\n");
      out.write("      <button type=\"button\" class=\"btn_member\">\n");
      out.write("        <div class=\"user_photo\">\n");
      out.write("          <figure class=\"user_img\">\n");
      out.write("            <img src=\"../images/Song.jpg\" alt=\"user_img\" />\n");
      out.write("          </figure>\n");
      out.write("        </div>\n");
      out.write("      </button>\n");
      out.write("\n");
      out.write("      <div class=\"layer_member\">\n");
      out.write("        <ul>\n");
      out.write("          <li>\n");
      out.write("            <img src=\"../images/Song.jpg\" alt=\"user_img\" /><span>송승현</span>\n");
      out.write("            <!-- 유저이미지, 이름 입력 -->\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"account.jsp\"><span>개인정보 수정</span><iconify-icon icon=\"la:edit-solid\" width=\"30\"></iconify-icon></a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"../jsp/logout.jsp\"><span>로그아웃</span><iconify-icon icon=\"material-symbols:logout\"\n");
      out.write("                width=\"25\"></iconify-icon></a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("    <!-- 마이페이지 사이드메뉴 -->\n");
      out.write("    <div class=\"nav\">\n");
      out.write("      <a href=\"../index.jsp\" id=\"logo2\">\n");
      out.write("        <img src=\"../images/logo.svg\" alt=\"logo\" />\n");
      out.write("      </a>\n");
      out.write("      <ul class=\"gnb\">\n");
      out.write("        <li class=\"gnb-menu\">\n");
      out.write("          <a href=\"profil.jsp\" class=\"menu-btn\">마이프로필</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"gnb-menu\">\n");
      out.write("          <a href=\"account.jsp\" class=\"menu-btn\">개인정보수정</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"gnb-menu\">\n");
      out.write("          <a href=\"authored_content.jsp\" class=\"menu-btn\">내가 작성한 글</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"gnb-menu\">\n");
      out.write("          <a href=\"Likestatus.jsp\" class=\"menu-btn\">좋아요 현황</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"gnb-menu\">\n");
      out.write("          <a href=\"matching_current.jsp\" class=\"menu-btn\">매칭현황</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"gnb-menu\">\n");
      out.write("          <a href=\"member_ship.jsp\" class=\"menu-btn\">멤버십</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"gnb-menu\">\n");
      out.write("          <a href=\"account_withdrawal.jsp\" class=\"menu-btn secession\">회원탈퇴</a>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("      <button type=\"button\" class=\"nav-icon\">\n");
      out.write("        <iconify-icon icon=\"ph:list-fill\"></iconify-icon>\n");
      out.write("      </button>\n");
      out.write("    </div>\n");
      out.write("  <main>\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"container_main\">\n");
      out.write("        <div class=\"content\">\n");
      out.write("          <h1>내가 작성한 글</h1>\n");
      out.write("          <h4>글 수정</h4>\n");
      out.write("        <form class=\"view\" action=\"updateAuthoredServlet\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("            <!-- 수정할 게시글 내용을 보여주는 부분 -->\n");
      out.write("            <div class=\"board_content\">\n");
      out.write("                <input type=\"hidden\" name=\"board_uid\" value=\"");
      out.print(resultSet.getString("uid"));
      out.write("\"/>\n");
      out.write("                <div class=\"title\">\n");
      out.write("                    <input type=\"text\" name=\"title\" value=\"");
      out.print(resultSet.getString("contact_title"));
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"info\">\n");
      out.write("                    <input type=\"text\" name=\"writer\" value=\"");
      out.print(resultSet.getString("user_name"));
      out.write("\">\n");
      out.write("                    <input type=\"password\" name=\"password\" maxlength=\"4\" value=\"");
      out.print(resultSet.getString("question_pw"));
      out.write("\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"cont\">\n");
      out.write("                    <textarea name=\"content\" id=\"textarea\"	oninput=\"autoResize()\">");
      out.print(resultSet.getString("contact_content"));
      out.write("</textarea>\n");
      out.write("                </div>\n");
      out.write("                <!-- 이미지 업로드 부분 -->\n");
      out.write("                <div class=\"image\">\n");
      out.write("                    <input type=\"file\" name=\"image\"");
      out.print(resultSet.getString("photo_url") );
      out.write(" >\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"btn_box\">\n");
      out.write("                <button type=\"submit\" class=\"btn_correction\">수정</button>\n");
      out.write("                <button><a href=\"authored_content.jsp\" class=\"btn_back\">취소</a></button>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("  </main>\n");
      out.write("  \n");
      out.write("  	");

	} else {
	
      out.write("\n");
      out.write("	<script>\n");
      out.write("		alert('접근권한이 없습니다.');\n");
      out.write("		location.href = \"../html/board_main.jsp\";\n");
      out.write("	</script>\n");
      out.write("	");

	}
	} else {
	
      out.write("\n");
      out.write("	<script>\n");
      out.write("		alert('게시글을 찾을 수 없습니다.');\n");
      out.write("		location.href = \"../html/board_main.jsp\";\n");
      out.write("	</script>\n");
      out.write("	");

	}

	resultSet.close();
	preparedStatement.close();
	conn.close();
	} else {
	// 세션이 없는 경우 로그인 페이지로 이동하도록 처리
	response.sendRedirect("login.jsp");
	}
	} catch (Exception e) {
	out.println("Error: " + e.getMessage());
	}
	
      out.write("\n");
      out.write("    <!-- 아래 footer 하단 고정 -->\n");
      out.write("    <footer class=\"footer\">\n");
      out.write("      <div class=\"footer-content\">\n");
      out.write("        <h3>(주)Re:connect</h3>\n");
      out.write("        <span>대표 : Recycle</span>\n");
      out.write("        <span>사업자등록번호 : 999-99-99999</span>\n");
      out.write("        <span>주소 : (34838)대전광역시 중구 중앙로121번길 20 (선화동 41) 2층</span>\n");
      out.write("        <span>Tel.042-222-2402</span>\n");
      out.write("        <ul class=\"footer-socials\">\n");
      out.write("          <li>\n");
      out.write("            <a href=\"index_logout.jsp\"><img src=\"../images/ico_image.svg\" alt=\"ico_image\" /></a>\n");
      out.write("            <!-- 임시로 로그아웃 넣어 놨음 -->\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"account_manager.jsp\"><img src=\"../images/ico_instagram.svg\" alt=\"ico_instagram\" /></a>\n");
      out.write("            <!-- 임시로 커플매니저페이지 넣어 놨음 -->\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"admin_manager_management.jsp\"><img src=\"../images/ico_youtube.svg\" alt=\"ico_youtube\" /></a>\n");
      out.write("            <!-- 임시로 관리자페이지 넣어 놨음 -->\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"footer-menu\">\n");
      out.write("          <p>\n");
      out.write("            copyright &copy;2023 by\n");
      out.write("            <a href=\"../index.jsp\">Re:connect.</a>\n");
      out.write("            All pictures cannot be copied without permission.\n");
      out.write("          </p>\n");
      out.write("          <ul class=\"f-menu\">\n");
      out.write("            <li><a href=\"../index.jsp\">Home</a></li>\n");
      out.write("            <li><a href=\"dash.jsp\">About</a></li>\n");
      out.write("            <li><a href=\"estimate.jsp\">Contact</a></li>\n");
      out.write("            <li><a href=\"FAQ.jsp\">FAQ</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </footer>\n");
      out.write("  <script src=\"../script/authored_content.js\"></script>\n");
      out.write("  <script src=\"https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
