/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-12-20 01:59:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bestmember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("		\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("	<title> 우수회원 | 마음을 다시 연결하는 결혼 정보 플랫폼 DASH </title>\n");
      out.write("	<meta charset=\"UTF-8\" />\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("	<meta name=\"keyworeds\" content=\"결혼, wedding, 결혼정보업체, DASH, Re:Connect, 듀오, 가연,\" />\n");
      out.write("	<meta name=\"description\" content=\"안녕하세요, 마음을 다시 연결하는 결혼 정보 플랫폼 DASH 입니다.\" />\n");
      out.write("	<link rel=\"icon\" href=\"../images/favicon.png\" />\n");
      out.write("	<link rel=\"stylesheet\" href=\"../CSS/bestmember.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"../CSS/reset.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"../CSS/header_style.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"../CSS/footer_style.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"../CSS/sidebar_style.css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<!-- 헤더 -->\n");
      out.write("	<header>\n");
      out.write("		<div class=\"header\">\n");
      out.write("			<div class=\"air\"></div>\n");
      out.write("			<a href=\"../index.jsp\" id=\"logo\">\n");
      out.write("				<img src=\"../images/logo.svg\" alt=\"로고\" />\n");
      out.write("			</a>\n");
      out.write("			<div class=\"login_menu\">\n");
      out.write("				<div id=\"loginStatus\"></div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<nav class=\"nav\">\n");
      out.write("			<a href=\"../index.jsp\" id=\"logo2\">\n");
      out.write("				<img src=\"../images/logo.svg\" alt=\"로고\" width=\"95\" />\n");
      out.write("			</a>\n");
      out.write("			<ul class=\"gnb\">\n");
      out.write("				<!-- <div id=\"test\"></div> -->\n");
      out.write("				<li class=\"gnb-menu\">\n");
      out.write("					<a href=\"#\" class=\"menu-btn\">회사소개</a>\n");
      out.write("					<ul class=\"sub-menu\">\n");
      out.write("						<li><a href=\"dash.jsp\">Dash란?</a></li>\n");
      out.write("						<li><a href=\"greeting.jsp\">인사말</a></li>\n");
      out.write("						<li><a href=\"manager.jsp\">커플 매니저 소개</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("				<li class=\"gnb-menu\">\n");
      out.write("					<a href=\"#\" class=\"menu-btn\">커뮤니티</a>\n");
      out.write("					<ul class=\"sub-menu\">\n");
      out.write("						<li><a href=\"notice.jsp\">공지사항</a></li>\n");
      out.write("						<li><a href=\"board_main.jsp\">문의하기</a></li>\n");
      out.write("						<li><a href=\"event.jsp\">이벤트</a></li>\n");
      out.write("						<li><a href=\"FAQ.jsp\">FAQ</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("				<li class=\"gnb-menu\">\n");
      out.write("					<a href=\"#\" class=\"menu-btn\">이용안내</a>\n");
      out.write("					<ul class=\"sub-menu\">\n");
      out.write("\n");
      out.write("						<li><a href=\"estimate.jsp\">상담예약</a></li>\n");
      out.write("						<li><a href=\"price.jsp\">이용요금</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("				<li class=\"gnb-menu\">\n");
      out.write("					<a href=\"#\" class=\"menu-btn\">후기정보</a>\n");
      out.write("					<ul class=\"sub-menu\">\n");
      out.write("						<li><a href=\"mgr_reviews.jsp\">매니저 후기</a></li>\n");
      out.write("						<li><a href=\"interview.jsp\">인터뷰</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("				<li class=\"gnb-menu\">\n");
      out.write("					<a href=\"#\" class=\"menu-btn\">매칭하기</a>\n");
      out.write("					<ul class=\"sub-menu\">\n");
      out.write("						<li><a href=\"matching.jsp\">Dash매칭</a></li>\n");
      out.write("						<li><a href=\"bestmember.jsp\">This Is Me</a></li>\n");
      out.write("					</ul>\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("			<button class=\"nav-icon\"><iconify-icon icon=\"ph:list-fill\"></iconify-icon></button>\n");
      out.write("\n");
      out.write("		</nav>\n");
      out.write("		<div class=\"dim-layer\"></div>\n");
      out.write("	</header>\n");
      out.write("\n");
      out.write("	<div>\n");
      out.write("		<nav class=\"side-bar\">\n");
      out.write("			<h2>매칭</h2>\n");
      out.write("			<ul class=\"sb-list\">\n");
      out.write("				<li><a href=\"matching.jsp\">Dash 매칭</a></li>\n");
      out.write("				<li><a href=\"bestmember.jsp\">This Is Me</a></li>\n");
      out.write("				<!-- <li><a href=\"#\">이용요금</a></li> -->\n");
      out.write("			</ul>\n");
      out.write("		</nav>\n");
      out.write("		<div id=\"box\"></div>\n");
      out.write("		<div class=\"content\">\n");
      out.write("			<div>\n");
      out.write("				<h1 class=\"title\">우 수 회 원</h1>\n");
      out.write("				<p class=\"sub-title\">메니저가 직접 선정한 DASH의 우수회원</p>\n");
      out.write("			</div>\n");
      out.write("			<swiper-container class=\"mySwiper\" loop=\"true\" pagination=\"true\" pagination-clickable=\"true\"\n");
      out.write("				navigation=\"true\" space-between=\"30\" centered-slides=\"true\" autoplay-delay=\"2500\"\n");
      out.write("				autoplay-disable-on-interaction=\"false\">\n");
      out.write("				<swiper-slide><img src=\"../images/Song.jpg\" width=\"1000px\" height=\"450px\" alt=\"고객사진\"></swiper-slide>\n");
      out.write("				<swiper-slide><img src=\"../images/An.jpg\" width=\"1000px\" height=\"450px\" alt=\"고객사진\"></swiper-slide>\n");
      out.write("				<swiper-slide><img src=\"../images/Yoo.jpg\" width=\"1000px\" height=\"450px\" alt=\"고객사진\"></swiper-slide>\n");
      out.write("\n");
      out.write("			</swiper-container>\n");
      out.write("\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number-1\">1</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number-2\">2</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number-3\">3</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number\">4</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number\">5</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number\">6</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number\">7</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number\">8</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number\">9</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"ranking-list\">\n");
      out.write("				<div class=\"ranking-number\">10</div>\n");
      out.write("				<img src=\"../images/An.jpg\" alt=\"인물\" width=\"70px\" height=\"70px\">\n");
      out.write("				<div class=\"ranking\">\n");
      out.write("					<p>유*나</p>\n");
      out.write("					<p>Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet consectetur adipisicing.</p>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"heart-container\" title=\"Like\">\n");
      out.write("					<input type=\"checkbox\" class=\"checkbox\" id=\"Give-It-An-Id\">\n");
      out.write("					<div class=\"svg-container\">\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-outline\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Zm-3.585,18.4a2.973,2.973,0,0,1-3.83,0C4.947,16.006,2,11.87,2,8.967a4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,11,8.967a1,1,0,0,0,2,0,4.8,4.8,0,0,1,4.5-5.05A4.8,4.8,0,0,1,22,8.967C22,11.87,19.053,16.006,13.915,20.313Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg viewBox=\"0 0 24 24\" class=\"svg-filled\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<path\n");
      out.write("								d=\"M17.5,1.917a6.4,6.4,0,0,0-5.5,3.3,6.4,6.4,0,0,0-5.5-3.3A6.8,6.8,0,0,0,0,8.967c0,4.547,4.786,9.513,8.8,12.88a4.974,4.974,0,0,0,6.4,0C19.214,18.48,24,13.514,24,8.967A6.8,6.8,0,0,0,17.5,1.917Z\">\n");
      out.write("							</path>\n");
      out.write("						</svg>\n");
      out.write("						<svg class=\"svg-celebrate\" width=\"100\" height=\"100\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("							<polygon points=\"10,10 20,20\"></polygon>\n");
      out.write("							<polygon points=\"10,50 20,50\"></polygon>\n");
      out.write("							<polygon points=\"20,80 30,70\"></polygon>\n");
      out.write("							<polygon points=\"90,10 80,20\"></polygon>\n");
      out.write("							<polygon points=\"90,50 80,50\"></polygon>\n");
      out.write("							<polygon points=\"80,80 70,70\"></polygon>\n");
      out.write("						</svg>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- 아래 footer 하단 고정 -->\n");
      out.write("	<footer class=\"footer\">\n");
      out.write("		<div class=\"footer-content\">\n");
      out.write("			<h3>(주)Re:connect</h3>\n");
      out.write("			<span>대표 : Recycle</span>\n");
      out.write("			<span>사업자등록번호 : 999-99-99999</span>\n");
      out.write("			<span>주소 : (34838)대전광역시 중구 중앙로121번길 20 (선화동 41) 2층</span>\n");
      out.write("			<span>Tel.042-222-2402</span>\n");
      out.write("			<ul class=\"footer-socials\">\n");
      out.write("				<li>\n");
      out.write("					<a href=\"index_logout.jsp\"><img src=\"../images/ico_image.svg\" alt=\"ico_image\" /></a>\n");
      out.write("					<!-- 임시로 로그아웃 넣어 놨음 -->\n");
      out.write("				</li>\n");
      out.write("				<li>\n");
      out.write("					<a href=\"account_manager.jsp\"><img src=\"../images/ico_instagram.svg\" alt=\"ico_instagram\" /></a>\n");
      out.write("					<!-- 임시로 커플매니저페이지 넣어 놨음 -->\n");
      out.write("				</li>\n");
      out.write("				<li>\n");
      out.write("					<a href=\"admin_manager_management.jsp\"><img src=\"../images/ico_youtube.svg\"\n");
      out.write("							alt=\"ico_youtube\" /></a>\n");
      out.write("					<!-- 임시로 관리자페이지 넣어 놨음 -->\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("			<div class=\"footer-menu\">\n");
      out.write("				<p>\n");
      out.write("					copyright &copy;2023 by\n");
      out.write("					<a href=\"../index.jsp\">Re:connect.</a>\n");
      out.write("					All pictures cannot be copied without permission.\n");
      out.write("				</p>\n");
      out.write("				<ul class=\"f-menu\">\n");
      out.write("					<li><a href=\"../index.jsp\">Home</a></li>\n");
      out.write("					<li><a href=\"dash.jsp\">About</a></li>\n");
      out.write("					<li><a href=\"estimate.jsp\">Contact</a></li>\n");
      out.write("					<li><a href=\"FAQ.jsp\">FAQ</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</footer>\n");
      out.write("	<script src=\"../script/header_script.js\"></script>\n");
      out.write("	<script src=\"../script/loginSession2.js\"></script>\n");
      out.write("	<script src=\"https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/swiper@10/swiper-element-bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
