/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-12-20 06:26:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;

public final class likeSubmit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
request.setCharacterEncoding("utf-8");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../jsp/user_list_component.jsp", out, false);
      out.write('\r');
      out.write('\n');

String userUid = (String) request.getAttribute("userUid");
String userId = (String) request.getAttribute("userId");
String userPw = (String) request.getAttribute("userPw");
String userName = (String) request.getAttribute("userName");
String userGender = (String) request.getAttribute("userGender");
String userBirth = (String) request.getAttribute("userBirth");
String userPhone = (String) request.getAttribute("userPhone");
String userEmail = (String) request.getAttribute("userEmail");
String userCountry = (String) request.getAttribute("userCountry");
String userCareer = (String) request.getAttribute("userCareer");
String userEducation = (String) request.getAttribute("userEducation");
String userHeight = (String) request.getAttribute("userHeight");
String userBody = (String) request.getAttribute("userBody");
String userSalary = (String) request.getAttribute("userSalary");
String userMarital = (String) request.getAttribute("userMarital");
String userChildren = (String) request.getAttribute("userChildren");
String userChildrenCount = (String) request.getAttribute("userChildrenCount");
String userBlood = (String) request.getAttribute("userBlood");
String userMBTI = (String) request.getAttribute("userMBTI");
String userReligion = (String) request.getAttribute("userReligion");
String userAlcohol = (String) request.getAttribute("userAlcohol");
String userAlcoholCount = (String) request.getAttribute("userAlcoholCount");
String userSmoking = (String) request.getAttribute("userSmoking");
String userHobbies = (String) request.getAttribute("userHobbies");
String userPersonality = (String) request.getAttribute("userPersonality");
String userMarriageValues = (String) request.getAttribute("userMarriageValues");
String userIntroduce = (String) request.getAttribute("userIntroduce");
String userPhotoURL = (String) request.getAttribute("userPhotoURL");
String imageName = (String) request.getAttribute("imageName");

String genderString = (userGender != null && userGender.equals("0")) ? "남자" : "여자";
String maritalString = (userMarital != null && userMarital.equals("0")) ? "초혼" : "재혼";
String childrenString = (userChildren != null && userChildren.equals("0")) ? "자녀 무" : "자녀 유";
String alcoholString = (userAlcohol != null && userAlcohol.equals("0")) ? "비음주" : "음주";
String smokingString = (userSmoking != null && userSmoking.equals("0")) ? "비흡연" : "흡연";

      out.write("\r\n");
      out.write("\r\n");

String user_uid = request.getParameter("user_uid");
String user_id = request.getParameter("user_id");
String user_pw = request.getParameter("user_pw");
String user_name = request.getParameter("user_name");
String user_phone = request.getParameter("user_phone");
String user_email = request.getParameter("user_email");
String user_auth = request.getParameter("user_auth");
String toUid = request.getParameter("toUid");

// MySQL 연결 정보
String url = "jdbc:mysql://192.168.0.71:3306/recycle?useUnicode=true&characterEncoding=UTF-8";
String username = "recycle";
String password = "1234";

Connection connection = null;
PreparedStatement checkStatement = null;
PreparedStatement insertStatement = null;

try {
    // MySQL 드라이버 로드
    Class.forName("com.mysql.cj.jdbc.Driver");

    // 데이터베이스에 연결
    connection = DriverManager.getConnection(url, username, password);

    // toUid가 null이면 "하트를 눌러주세요" 알림 창 띄우기
    if (toUid == null) {

      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            alert(\"하트를 눌러주세요\");\r\n");
      out.write("            window.history.back();\r\n");
      out.write("        </script>\r\n");

    } else {
        // 중복 확인 쿼리 작성
        boolean alreadyLiked = false;
        String checkSql = "SELECT * FROM `like` WHERE from_user = ? AND to_user = ?";
        checkStatement = connection.prepareStatement(checkSql);

        // 파라미터 설정
        checkStatement.setString(1, userUid); // from
        checkStatement.setString(2, toUid); // to

        // 중복 확인 쿼리 실행
        ResultSet resultSet = checkStatement.executeQuery();

        if (resultSet.next()) {
            // 이미 좋아요를 눌렀을 경우
             alreadyLiked = true;

      out.write("\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                alert(\"이미 좋아요를 누르셨습니다.\");\r\n");
      out.write("                window.history.back();\r\n");
      out.write("            </script>\r\n");

        } else {
            // 중복이 아니라면 좋아요를 추가
            // 좋아요 추가 쿼리 작성
            String insertSql = "INSERT INTO `like` (from_user, to_user) VALUES (?, ?)";
            insertStatement = connection.prepareStatement(insertSql);

            // 파라미터 설정
            insertStatement.setString(1, userUid); // from
            insertStatement.setString(2, toUid); // to

            // 좋아요 추가 쿼리 실행
            int rowsAffected = insertStatement.executeUpdate();

            if (rowsAffected > 0) {

      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    alert(\"좋아요를 보내셨습니다.\");\r\n");
      out.write("                    window.history.back();\r\n");
      out.write("                </script>\r\n");

            } else {
                // 등록 실패

      out.write("\r\n");
      out.write("                <script>\r\n");
      out.write("                    alert('등록 실패, 빠진 정보가 없는지 확인하시오.');\r\n");
      out.write("                    window.history.back();\r\n");
      out.write("                </script>\r\n");

            }
            // like 테이블에서 A가 B를, B가 A를 좋아요한 경우 찾기
            String likeQuery = "SELECT COUNT(*) AS count_likes FROM `like` WHERE (to_user = ? AND from_user = ?) OR (to_user = ? AND from_user = ?)";
            PreparedStatement likeStatement = connection.prepareStatement(likeQuery);
            likeStatement.setString(1, toUid);
            likeStatement.setString(2, userUid);
            likeStatement.setString(3, userUid);
            likeStatement.setString(4, toUid);
            ResultSet likeResult = likeStatement.executeQuery();
            
         // 2에서 5까지 랜덤한 double 값 생성
            double randomValue = 2 + Math.random() * 3;

            // double 값을 문자열로 변환
            String stringValue = Double.toString(randomValue);
            
            if (likeResult.next() && likeResult.getInt("count_likes") == 2) {
                // 두 사용자가 서로를 좋아요한 경우, matches 테이블에 새로운 매치 추가
                String insertMatchQuery = "INSERT INTO matches (user1_id, user2_id, matched_date, manager_id) VALUES (?, ?, NOW(), ?)";
                PreparedStatement insertMatchStatement = connection.prepareStatement(insertMatchQuery);
                insertMatchStatement.setString(1, toUid);
                insertMatchStatement.setString(2, userUid);
                insertMatchStatement.setString(3, stringValue);
                insertMatchStatement.executeUpdate();
                insertMatchStatement.close();
            }
        }
    }
} catch (Exception e) {
    e.printStackTrace();
} finally {
    // 리소스 해제
    try {
        if (checkStatement != null) {
            checkStatement.close();
        }
        if (insertStatement != null) {
            insertStatement.close();
        }
        if (connection != null) {
            connection.close();
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
