/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-12-06 07:23:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;

public final class account_005fmanager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
request.setCharacterEncoding("utf-8");
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../jsp/user_list_component.jsp", out, false);
      out.write("  \n");
      out.write("\n");

String userId = (String) request.getAttribute("userId");
String userPw = (String) request.getAttribute("userPw");
String userName = (String) request.getAttribute("userName");
String userGender = (String) request.getAttribute("userGender");
String userBirth = (String) request.getAttribute("userBirth");
String userPhone = (String) request.getAttribute("userPhone");
String userEmail = (String) request.getAttribute("userEmail");
String userCountry = (String) request.getAttribute("userCountry");
String userCareer = (String) request.getAttribute("userCareer");
String userEducation = (String) request.getAttribute("userEducation");
String userHeight = (String) request.getAttribute("userHeight");
String userBody = (String) request.getAttribute("userBody");
String userSalary = (String) request.getAttribute("userSalary");
String userMarital = (String) request.getAttribute("userMarital");
String userChildren = (String) request.getAttribute("userChildren");
String userChildrenCount = (String) request.getAttribute("userChildrenCount");
String userBlood = (String) request.getAttribute("userBlood");
String userMBTI = (String) request.getAttribute("userMBTI");
String userReligion = (String) request.getAttribute("userReligion");
String userAlcohol = (String) request.getAttribute("userAlcohol");
String userAlcoholCount = (String) request.getAttribute("userAlcoholCount");
String userSmoking = (String) request.getAttribute("userSmoking");
String userHobbies = (String) request.getAttribute("userHobbies");
String userPersonality = (String) request.getAttribute("userPersonality");
String userMarriageValues = (String) request.getAttribute("userMarriageValues");
String userIntroduce = (String) request.getAttribute("userIntroduce");
String userPhotoURL = (String) request.getAttribute("userPhotoURL");
String imageName = (String) request.getAttribute("imageName");


      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("	<title>마이페이지 | 마음을 다시 연결하는 결혼 정보 플랫폼 DASH</title>\n");
      out.write("	<meta charset=\"UTF-8\" />\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("	<meta name=\"keyworeds\" content=\"결혼, wedding, 결혼정보업체, DASH, Re:Connect, 듀오, 가연,\" />\n");
      out.write("	<meta name=\"description\" content=\"안녕하세요, 마음을 다시 연결하는 결혼 정보 플랫폼 DASH 입니다.\" />\n");
      out.write("	<link rel=\"icon\" href=\"../images/favicon.png\" />\n");
      out.write("	<link rel=\"stylesheet\" href=\"../CSS/account_manager.css\" />\n");
      out.write("	<link rel=\"stylesheet\" href=\"../CSS/footer_style.css\" />\n");
      out.write("	<link rel=\"stylesheet\" href=\"../CSS/reset.css\" />\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	<header class=\"account_header\">\n");
      out.write("		<div class=\"header_btn\">\n");
      out.write("			<div class=\"message_badge\">\n");
      out.write("				<button type=\"button\" class=\"btn_messenger\" onclick=\"\">메신저</button>\n");
      out.write("				<span class=\"push_num\" style=\"display: none\">0</span>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"alarm_badge\">\n");
      out.write("				<button type=\"button\" class=\"btn_alarm\" onclick=\"\">알림</button>\n");
      out.write("				<span class=\"push_num\" style=\"display: none\">0</span>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"member\">\n");
      out.write("			<button type=\"button\" class=\"btn_member\">\n");
      out.write("				<div class=\"user_photo\">\n");
      out.write("					<figure class=\"user_img\">\n");
      out.write("						<img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/");
      out.print( imageName );
      out.write("\" alt=\"user_img\" />\n");
      out.write("					</figure>\n");
      out.write("				</div>\n");
      out.write("			</button>\n");
      out.write("\n");
      out.write("			<div class=\"layer_member\">\n");
      out.write("				<ul>\n");
      out.write("					<li>\n");
      out.write("						<img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/");
      out.print( imageName );
      out.write("\" alt=\"user_img\" /><span>");
      out.print(userName );
      out.write("</span>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("						<a href=\"account_manager.jsp\"><span>개인정보 수정</span><iconify-icon icon=\"la:edit-solid\"\n");
      out.write("								width=\"30\"></iconify-icon></a>\n");
      out.write("					</li>\n");
      out.write("					<li>\n");
      out.write("					<li><a href=\"../jsp/logout.jsp\"><span>로그아웃</span>\n");
      out.write("							<iconify-icon icon=\"material-symbols:logout\" width=\"25\"></iconify-icon></a>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</header>\n");
      out.write("  <div class=\"nav\">\n");
      out.write("    <a href=\"../index.jsp\" id=\"logo2\">\n");
      out.write("      <img src=\"../images/logo.svg\" alt=\"logo\" />\n");
      out.write("    </a>\n");
      out.write("    <ul class=\"gnb\">\n");
      out.write("      <li class=\"gnb-menu\">\n");
      out.write("        <a href=\"account_manager.jsp\" class=\"menu-btn\">마이페이지</a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"gnb-menu\">\n");
      out.write("        <a href=\"post_management.jsp\" class=\"menu-btn\">게시물 관리</a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"gnb-menu\">\n");
      out.write("        <a href=\"user_management.jsp\" class=\"menu-btn\">회원관리</a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"gnb-menu\">\n");
      out.write("        <a href=\"user_estimate_manager.jsp\" class=\"menu-btn\">상담예약 확인</a>\n");
      out.write("      </li>\n");
      out.write("      <li class=\"gnb-menu\">\n");
      out.write("        <a href=\"matching_management.jsp\" class=\"menu-btn\">DASH 매칭</a>\n");
      out.write("      </li>\n");
      out.write("    </ul>\n");
      out.write("    <button type=\"button\" class=\"nav-icon\">\n");
      out.write("      <iconify-icon icon=\"ph:list-fill\"></iconify-icon>\n");
      out.write("    </button>\n");
      out.write("  </div>\n");
      out.write("	<main>\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"container_main\">\n");
      out.write("				<div class=\"content\">\n");
      out.write("					<h1>개인정보 수정</h1>\n");
      out.write("					<div class=\"privacy_update\">\n");
      out.write("						<form action=\"#\" method=\"post\" id=\"privacy_form\" enctype=\"multipart/form-data\">\n");
      out.write("							<!-- 프로필 사진 업로드 섹션 -->\n");
      out.write("							<div class=\"photo_wrap\">\n");
      out.write("								<span class=\"photo\" id=\"myhome_profile_photo\">\n");
      out.write("									<img src=\"");
      out.print( request.getContextPath() );
      out.write("/images/");
      out.print( imageName );
      out.write("\" alt=\"user_img\" />\n");
      out.write("								</span>\n");
      out.write("								<span class=\"photo_border\"></span>\n");
      out.write("								<button type=\"button\" class=\"btn_photo\" aria-label=\"프로필 편집/삭제\" aria-haspopup=\"menu\"\n");
      out.write("									onclick=\"toggleEditMenu()\">\n");
      out.write("									&#9776;\n");
      out.write("								</button>\n");
      out.write("								<div class=\"photo_edit_btn\" id=\"edit_menu\">\n");
      out.write("									<input type=\"file\" id=\"profile_picture_input\" accept=\"image/*\"\n");
      out.write("										style=\"display: none\" />\n");
      out.write("									<label for=\"profile_picture_input\"><span>프로필 사진 업로드</span></label>\n");
      out.write("									<button type=\"button\" id=\"btnPhotoDelete\" onclick=\"deleteProfilePhoto()\">\n");
      out.write("										<span>프로필 삭제</span>\n");
      out.write("									</button>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<!-- 기본 정보 섹션 -->\n");
      out.write("							<div class=\"privacy_info\" id=\"basic_info\">\n");
      out.write("								<!-- 내용을 여기에 추가하세요. -->\n");
      out.write("								<div class=\"info-id\">\n");
      out.write("									<input type=\"text\" name=\"user_id\" value=\"");
      out.print(userId );
      out.write("\" maxlength=\"10\" required\n");
      out.write("										disabled />\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<div class=\"info-name\">\n");
      out.write("									<input type=\"text\" name=\"user_npassword\" value=\"**********\" placeholder=\"비밀번호\"\n");
      out.write("										maxlength=\"10\" required />\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<div class=\"info-name\">\n");
      out.write("									<input type=\"text\" name=\"user_name\" placeholder=\"이름\" maxlength=\"10\" required value=\"");
      out.print(userName );
      out.write("\" />\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<div class=\"info-age\">\n");
      out.write("									<input type=\"text\" name=\"user_age\" placeholder=\"생년월일\" maxlength=\"8\" required value=\"");
      out.print(userBirth );
      out.write("\"/>\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<div class=\"info-mail\">\n");
      out.write("									<input type=\"text\" name=\"user_mail\" placeholder=\"E-mail\" required value=\"");
      out.print(userEmail );
      out.write("\"/>\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<div class=\"info-phone\">\n");
      out.write("									<input type=\"text\" name=\"user_phone\" id=\"user_phone\" placeholder=\"연락처\"\n");
      out.write("										maxlength=\"13\" required oninput=\"autoHyphen2(this)\" value=\"");
      out.print(userPhone );
      out.write("\"/>\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("								<div class=\"info-emerPhone\">\n");
      out.write("									<input type=\"text\" name=\"user_emerPhone\" id=\"user_emerPhone\" placeholder=\"비상연락처\"\n");
      out.write("										maxlength=\"13\" oninput=\"autoHyphen2(this)\" required />\n");
      out.write("								</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("								<div class=\"about_me\">\n");
      out.write("									<textarea name=\"about_me_text\" id=\"about_me_text\" placeholder=\"자기소개를 통해 자신을 표현해보세요.\"\n");
      out.write("										required value=\"");
      out.print(userIntroduce );
      out.write("\"></textarea>\n");
      out.write("								</div>\n");
      out.write("								<!-- \n");
      out.write("                <button type=\"button\" id=\"next_page\" onclick=\"showPage('detailed_info')\">다음</button> -->\n");
      out.write("								<button type=\"submit\" id=\"submit-privacy\">저장하기</button>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("							<!-- 상세 정보 섹션 -->\n");
      out.write("							<div class=\"privacy_info\" id=\"detailed_info\" style=\"display: none;\">\n");
      out.write("								<!-- 내용을 여기에 추가하세요. -->\n");
      out.write("								<h2 class=\"privacy_info_marriage privacy_info_header\">자기소개</h2>\n");
      out.write("								<!-- <button type=\"button\" id=\"prev_page3\" onclick=\"showPage('additional_info2')\">이전</button> -->\n");
      out.write("								<button type=\"button\" id=\"prev_page\" onclick=\"showPage('basic_info')\">이전</button>\n");
      out.write("								<button type=\"submit\" id=\"submit-privacy\">저장하기</button>\n");
      out.write("								<!-- <button type=\"button\" id=\"next_page2\" onclick=\"showPage('additional_info1')\">다음</button> -->\n");
      out.write("							</div>\n");
      out.write("							<!-- 추가 정보 페이지 1 -->\n");
      out.write("\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</main>\n");
      out.write("	<!-- 아래 footer 하단 고정 -->\n");
      out.write("	<footer class=\"footer\">\n");
      out.write("		<div class=\"footer-content\">\n");
      out.write("			<h3>(주)Re:connect</h3>\n");
      out.write("			<span>대표 : Recycle</span>\n");
      out.write("			<span>사업자등록번호 : 999-99-99999</span>\n");
      out.write("			<span>주소 : (34838)대전광역시 중구 중앙로121번길 20 (선화동 41) 2층</span>\n");
      out.write("			<span>Tel.042-222-2402</span>\n");
      out.write("			<ul class=\"footer-socials\">\n");
      out.write("				<li>\n");
      out.write("					<a href=\"index_logout.jsp\"><img src=\"../images/ico_image.svg\" alt=\"ico_image\" /></a>\n");
      out.write("					<!-- 임시로 로그아웃 넣어 놨음 -->\n");
      out.write("				</li>\n");
      out.write("				<li>\n");
      out.write("					<a href=\"account_manager.jsp\"><img src=\"../images/ico_instagram.svg\" alt=\"ico_instagram\" /></a>\n");
      out.write("					<!-- 임시로 커플매니저페이지 넣어 놨음 -->\n");
      out.write("				</li>\n");
      out.write("				<li>\n");
      out.write("					<a href=\"admin_manager_management.jsp\"><img src=\"../images/ico_youtube.svg\"\n");
      out.write("							alt=\"ico_youtube\" /></a>\n");
      out.write("					<!-- 임시로 관리자페이지 넣어 놨음 -->\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("			<div class=\"footer-menu\">\n");
      out.write("				<p>\n");
      out.write("					copyright &copy;2023 by\n");
      out.write("					<a href=\"../index.jsp\">Re:connect.</a>\n");
      out.write("					All pictures cannot be copied without permission.\n");
      out.write("				</p>\n");
      out.write("				<ul class=\"f-menu\">\n");
      out.write("					<li><a href=\"../index.jsp\">Home</a></li>\n");
      out.write("					<li><a href=\"dash.jsp\">About</a></li>\n");
      out.write("					<li><a href=\"estimate.jsp\">Contact</a></li>\n");
      out.write("					<li><a href=\"FAQ.jsp\">FAQ</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</footer>\n");
      out.write("	<script src=\"../script/account_manager.js\"></script>\n");
      out.write("	<script src=\"https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
