/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-12-01 03:18:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class interview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title> 인터뷰 | 마음을 다시 연결하는 결혼 정보 플랫폼 DASH </title>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("  <meta name=\"keyworeds\" content=\"결혼, wedding, 결혼정보업체, DASH, Re:Connect, 듀오, 가연,\" />\r\n");
      out.write("  <meta name=\"description\" content=\"안녕하세요, 마음을 다시 연결하는 결혼 정보 플랫폼 DASH 입니다.\" />\r\n");
      out.write("  <link rel=\"icon\" href=\"../images/favicon.png\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../CSS/interview_style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../CSS/reset.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../CSS/header_style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../CSS/footer_style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../CSS/sidebar_style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- 헤더 -->\r\n");
      out.write("  <header>\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("      <div class=\"air\"></div>\r\n");
      out.write("      <a href=\"../index.jsp\" id=\"logo\">\r\n");
      out.write("        <img src=\"../images/logo.svg\" alt=\"로고\" />\r\n");
      out.write("      </a>\r\n");
      out.write("      <div class=\"login_menu\">\r\n");
      out.write("<div id=\"loginStatus\"></div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"nav\">\r\n");
      out.write("      <a href=\"../index.jsp\" id=\"logo2\">\r\n");
      out.write("        <img src=\"../images/logo.svg\" alt=\"로고\" width=\"95\"/>\r\n");
      out.write("      </a>\r\n");
      out.write("      <ul class=\"gnb\">\r\n");
      out.write("        <!-- <div id=\"test\"></div> -->\r\n");
      out.write("        <li class=\"gnb-menu\">\r\n");
      out.write("          <a href=\"#\" class=\"menu-btn\">회사소개</a>\r\n");
      out.write("          <ul class=\"sub-menu\">\r\n");
      out.write("            <li><a href=\"dash.jsp\">Dash란?</a></li>\r\n");
      out.write("            <li><a href=\"greeting.jsp\">인사말</a></li>\r\n");
      out.write("            <li><a href=\"manager.jsp\">커플 매니저 소개</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"gnb-menu\">\r\n");
      out.write("          <a href=\"#\" class=\"menu-btn\">커뮤니티</a>\r\n");
      out.write("          <ul class=\"sub-menu\">\r\n");
      out.write("            <li><a href=\"notice.jsp\">공지사항</a></li>\r\n");
      out.write("            <li><a href=\"board_main.jsp\">문의하기</a></li>\r\n");
      out.write("            <li><a href=\"event.jsp\">이벤트</a></li>\r\n");
      out.write("            <li><a href=\"FAQ.jsp\">FAQ</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"gnb-menu\">\r\n");
      out.write("          <a href=\"#\" class=\"menu-btn\">이용안내</a>\r\n");
      out.write("          <ul class=\"sub-menu\">\r\n");
      out.write("            \r\n");
      out.write("            <li><a href=\"estimate.jsp\">상담예약</a></li>\r\n");
      out.write("            <li><a href=\"price.jsp\">이용요금</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"gnb-menu\">\r\n");
      out.write("          <a href=\"#\" class=\"menu-btn\">후기정보</a>\r\n");
      out.write("          <ul class=\"sub-menu\">\r\n");
      out.write("            <li><a href=\"mgr_reviews.jsp\">매니저 후기</a></li>\r\n");
      out.write("            <li><a href=\"interview.jsp\">인터뷰</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("        <li class=\"gnb-menu\">\r\n");
      out.write("          <a href=\"#\" class=\"menu-btn\">매칭하기</a>\r\n");
      out.write("          <ul class=\"sub-menu\">\r\n");
      out.write("            <li><a href=\"matching.jsp\">Dash매칭</a></li>\r\n");
      out.write("            <li><a href=\"bestmember.jsp\">This Is Me</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <button class=\"nav-icon\"><iconify-icon icon=\"ph:list-fill\"></iconify-icon></button>\r\n");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("    <div class=\"dim-layer\"></div>\r\n");
      out.write("  </header>\r\n");
      out.write("\r\n");
      out.write("  <!-- 메인 -->\r\n");
      out.write("  <main>\r\n");
      out.write("    <!-- 사이드바 -->\r\n");
      out.write("    <nav class=\"side-bar\">\r\n");
      out.write("      <h2>후기정보</h2>\r\n");
      out.write("      <ul class=\"sb-list\">\r\n");
      out.write("        <li><a href=\"mgr_reviews.jsp\">매니저 후기</a></li>\r\n");
      out.write("        <li><a href=\"interview.jsp\">인터뷰</a></li>\r\n");
      out.write("        <!-- <li><a href=\"#\">이용요금</a></li> -->\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- 본문 -->\r\n");
      out.write("    <div id=\"box\"></div>\r\n");
      out.write("    <h2 id=\"title\">인터뷰</h2>\r\n");
      out.write("    <p id=\"sub-title\">우리들의 사랑을 전달합니다</p>\r\n");
      out.write("    <div id=\"slideShow\">\r\n");
      out.write("      <ul class=\"slides\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <img src=\"../images/인터뷰1.png\" alt=\"\">\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <img src=\"../images/인터뷰2.png\" alt=\"\">\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <img src=\"../images/인터뷰3.png\" alt=\"\">\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <img src=\"../images/인터뷰4.png\" alt=\"\">\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <img src=\"../images/인터뷰5.png\" alt=\"\">\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("          <img src=\"../images/인터뷰6.png\" alt=\"\">\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("      <p class=\"controller\">\r\n");
      out.write("        <span class=\"prev\">&lang;</span>\r\n");
      out.write("        <span class=\"next\">&rang;</span>\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 리뷰 -->\r\n");
      out.write("    <div class=\"review-container\">\r\n");
      out.write("      <h2>후기</h2>\r\n");
      out.write("      <form id=\"review-board\" action=\"#\" method=\"post\">\r\n");
      out.write("        <div class=\"review \">\r\n");
      out.write("\r\n");
      out.write("          <h4>anda******</h4>\r\n");
      out.write("          <p>다시 덕분에 완벽한 파트너를 만났습니다. 프로페셔널한 서비스와 정확한 매칭으로 인해 우리의 인연이 시작되었습니다. 진심으로 감사합니다!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"review\">\r\n");
      out.write("\r\n");
      out.write("          <h4>qs******</h4>\r\n");
      out.write("          <p>다시는 최고였습니다! 간단한 프로필 작성 후, 내 인생의 반쪽을 만났어요. 정말로 감사합니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"review \">\r\n");
      out.write("\r\n");
      out.write("          <h4>anda******</h4>\r\n");
      out.write("          <p>우리의 사랑 이야기는 다시로 시작되었습니다. 정말 행복해요!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"review\">\r\n");
      out.write("\r\n");
      out.write("          <h4>qs******</h4>\r\n");
      out.write("          <p>결혼정보업체로 다시를 선택한 것은 최고의 선택 중 하나였어요. 우리를 함께 이어주셔서 감사합니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- 리뷰 등록창 -->\r\n");
      out.write("      <form id=\"review-form\" action=\"#\" method=\"post\">\r\n");
      out.write("        <div class=\"name\">\r\n");
      out.write("          <h4>이름</h4>\r\n");
      out.write("          <input type=\"text\" id=\"name\" name=\"title\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("          <h4>내용</h4>\r\n");
      out.write("          <textarea id=\"content\" name=\"content\" rows=\"4\" cols=\"50\" required></textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"button\">\r\n");
      out.write("          <button type=\"submit\">등록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </main>\r\n");
      out.write("    <!-- 아래 footer 하단 고정 -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("      <div class=\"footer-content\">\r\n");
      out.write("        <h3>(주)Re:connect</h3>\r\n");
      out.write("        <span>대표 : Recycle</span>\r\n");
      out.write("        <span>사업자등록번호 : 999-99-99999</span>\r\n");
      out.write("        <span>주소 : (34838)대전광역시 중구 중앙로121번길 20 (선화동 41) 2층</span>\r\n");
      out.write("        <span>Tel.042-222-2402</span>\r\n");
      out.write("        <ul class=\"footer-socials\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"index_logout.jsp\"><img src=\"../images/ico_image.svg\" alt=\"ico_image\" /></a>\r\n");
      out.write("            <!-- 임시로 로그아웃 넣어 놨음 -->\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"account_manager.jsp\"><img src=\"../images/ico_instagram.svg\" alt=\"ico_instagram\" /></a>\r\n");
      out.write("            <!-- 임시로 커플매니저페이지 넣어 놨음 -->\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"admin_manager_management.jsp\"><img src=\"../images/ico_youtube.svg\" alt=\"ico_youtube\" /></a>\r\n");
      out.write("            <!-- 임시로 관리자페이지 넣어 놨음 -->\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"footer-menu\">\r\n");
      out.write("          <p>\r\n");
      out.write("            copyright &copy;2023 by\r\n");
      out.write("            <a href=\"../index.jsp\">Re:connect.</a>\r\n");
      out.write("            All pictures cannot be copied without permission.\r\n");
      out.write("          </p>\r\n");
      out.write("          <ul class=\"f-menu\">\r\n");
      out.write("            <li><a href=\"../index.jsp\">Home</a></li>\r\n");
      out.write("            <li><a href=\"dash.jsp\">About</a></li>\r\n");
      out.write("            <li><a href=\"estimate.jsp\">Contact</a></li>\r\n");
      out.write("            <li><a href=\"FAQ.jsp\">FAQ</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("  <script src=\"https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js\"></script>\r\n");
      out.write("  <script src=\"../script/header_script.js\"></script>\r\n");
      out.write("  <script src=\"../script/interview_script.js\"></script>\r\n");
      out.write("  <script src=\"../script/loginSession2.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
