/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.82
 * Generated at: 2023-12-19 07:03:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("  <head>\n");
      out.write("    <title>DASH 결혼정보회사:: 1234-5678</title>\n");
      out.write("    <meta charset=\"UTF-8\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("    <meta\n");
      out.write("      name=\"keyworeds\"\n");
      out.write("      content=\"결혼, wedding, 결혼정보업체, DASH, Re:Connect, 듀오, 가연,\"\n");
      out.write("    />\n");
      out.write("    <meta\n");
      out.write("      name=\"description\"\n");
      out.write("      content=\"안녕하세요, 마음을 다시 연결하는 결혼 정보 플랫폼 DASH 입니다.\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <!-- 가장 기본이고 우선순위가 약한거 순서대로 위에 두는거라 reset을 맨위에 -->\n");
      out.write("    <link rel=\"icon\" href=\"images/favicon.png\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/reset.css\" />\n");
      out.write("\n");
      out.write("    <!-- header footer를 그 바로 밑에  -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/header_footer.css\" />\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"../CSS/header_style.css\" />\n");
      out.write("    <link rel=\"stylesheet\" href=\"../CSS/footer_style.css\" /> -->\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/index.css\" />\n");
      out.write("    <!-- 다 때려넣는 css는 index.css로 정리했음 -->\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("    <!-- 헤더 -->\n");
      out.write("    <header>\n");
      out.write("      <div class=\"header\">\n");
      out.write("        <div class=\"air\"></div>\n");
      out.write("        <a href=\"index.jsp\" id=\"logo\">\n");
      out.write("          <img src=\"images/logo.svg\" alt=\"로고\" />\n");
      out.write("        </a>\n");
      out.write("        <div class=\"login_menu\" id=\"loginMenu\">\n");
      out.write("          <div id=\"loginStatus\"></div>\n");
      out.write("          <!-- 여기바뀜 -->\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <nav class=\"nav\">\n");
      out.write("        <a href=\"html/index.jsp\" id=\"logo2\">\n");
      out.write("          <img src=\"images/logo.svg\" alt=\"로고\" width=\"95\" />\n");
      out.write("        </a>\n");
      out.write("        <ul class=\"gnb\">\n");
      out.write("          <!-- <div id=\"test\"></div> -->\n");
      out.write("          <li class=\"gnb-menu\">\n");
      out.write("            <a href=\"#\" class=\"menu-btn\">회사소개</a>\n");
      out.write("            <ul class=\"sub-menu\">\n");
      out.write("              <li><a href=\"html/dash.jsp\">Dash란?</a></li>\n");
      out.write("              <li><a href=\"html/greeting.jsp\">인사말</a></li>\n");
      out.write("              <li><a href=\"html/manager.jsp\">커플 매니저 소개</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li class=\"gnb-menu\">\n");
      out.write("            <a href=\"#\" class=\"menu-btn\">커뮤니티</a>\n");
      out.write("            <ul class=\"sub-menu\">\n");
      out.write("              <li><a href=\"html/notice.jsp\">공지사항</a></li>\n");
      out.write("              <li><a href=\"html/board_main.jsp\">문의하기</a></li>\n");
      out.write("              <li><a href=\"html/event.jsp\">이벤트</a></li>\n");
      out.write("              <li><a href=\"html/FAQ.jsp\">FAQ</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li class=\"gnb-menu\">\n");
      out.write("            <a href=\"#\" class=\"menu-btn\">이용안내</a>\n");
      out.write("            <ul class=\"sub-menu\">\n");
      out.write("              <li><a href=\"html/estimate.jsp\">상담예약</a></li>\n");
      out.write("              <li><a href=\"html/price.jsp\">이용요금</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li class=\"gnb-menu\">\n");
      out.write("            <a href=\"#\" class=\"menu-btn\">후기정보</a>\n");
      out.write("            <ul class=\"sub-menu\">\n");
      out.write("              <li><a href=\"html/mgr_reviews.jsp\">매니저 후기</a></li>\n");
      out.write("              <li><a href=\"html/interview.jsp\">인터뷰</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li class=\"gnb-menu\">\n");
      out.write("            <a href=\"#\" class=\"menu-btn\">매칭하기</a>\n");
      out.write("            <ul class=\"sub-menu\">\n");
      out.write("              <li><a href=\"html/matching.jsp\">Dash매칭</a></li>\n");
      out.write("              <li><a href=\"html/bestmember.jsp\">This Is Me</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <button class=\"nav-icon\">\n");
      out.write("          <iconify-icon icon=\"ph:list-fill\"></iconify-icon>\n");
      out.write("        </button>\n");
      out.write("      </nav>\n");
      out.write("      <div class=\"dim-layer\"></div>\n");
      out.write("    </header>\n");
      out.write("\n");
      out.write("    <!-- wrap은 감싼다는 의미기에 보통 이렇게 전체를 감싸는 코드에 한번 감싸줌 -->\n");
      out.write("    <div class=\"index_wrap\">\n");
      out.write("      <section class=\"area_1\"></section>\n");
      out.write("\n");
      out.write("      <section class=\"area_2\">\n");
      out.write("        <div>\n");
      out.write("          우리 다시 만나요,\n");
      out.write("          <br />\n");
      out.write("          우연히.\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <section class=\"area_3\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"inner1\"></div>\n");
      out.write("          <div class=\"inner2\">\n");
      out.write("            <h5>\n");
      out.write("              <span>그물망</span>\n");
      out.write("              신원인증\n");
      out.write("            </h5>\n");
      out.write("\n");
      out.write("            <p>\n");
      out.write("              제3자 위탁없이\n");
      out.write("              <br />\n");
      out.write("              100% 본사 신원인증팀이 진행합니다.\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            <button>\n");
      out.write("              <a href=\"html/dash.jsp\">자세히 보러가기-></a>\n");
      out.write("            </button>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("              <p>신속한만남주선</p>\n");
      out.write("              <p>무제한프로필 추천</p>\n");
      out.write("              <p>2:1 맞춤관리</p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <section class=\"area_4\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"inner_1\">\n");
      out.write("            <div>\n");
      out.write("              <ul>\n");
      out.write("                <li>서비스안내</li>\n");
      out.write("                <li>\n");
      out.write("                  <img src=\"images/dash_se.svg\" alt=\"\" />\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                  DASH의 서비스가 궁금하신가요?\n");
      out.write("                  <br />\n");
      out.write("                  회원님께 적합한 서비스를 제안해드립니다.\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <button>자세히 보러가기 -></button>\n");
      out.write("              </a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <div class=\"service_1\"></div>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"#\">\n");
      out.write("              <div class=\"service_2\"></div>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"inner_2\">\n");
      out.write("            <div class=\"profile\">\n");
      out.write("              <div class=\"profile_img\">\n");
      out.write("                <img src=\"images/humen_01.svg\" />\n");
      out.write("              </div>\n");
      out.write("              <div class=\"txt_content\">\n");
      out.write("                <h6>송승현</h6>\n");
      out.write("                <p>카페매니저/서울본점</p>\n");
      out.write("                <p>\n");
      out.write("                  서로에게 기가 막힌 타이밍에 서로의 인생에 자연스레 등장해 주는\n");
      out.write("                  것이 그것이 \"인연\" 입니다. 인연은 기다리는 것이 아닙니다.\n");
      out.write("                  선택과 용기와 결단이 필요합니다.\n");
      out.write("                </p>\n");
      out.write("\n");
      out.write("                <div class=\"btn_group\">\n");
      out.write("                  <button class=\"btn_01\">\n");
      out.write("                    <a href=\"#\">매니저 소개</a>\n");
      out.write("                  </button>\n");
      out.write("                  <button><a href=\"#\">상담하기</a></button>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"profile\">\n");
      out.write("              <div class=\"profile_img\">\n");
      out.write("                <img src=\"images/humen_02.svg\" />\n");
      out.write("              </div>\n");
      out.write("              <div class=\"txt_content\">\n");
      out.write("                <h6>유세나</h6>\n");
      out.write("                <p>카페매니저/서울본점</p>\n");
      out.write("                <p>\n");
      out.write("                  당신의 조건과 마음의 목소리를 듣고, 어울리는 인연을 찾아주는\n");
      out.write("                  사랑의 큐피트 유세나 커플매니저 입니다.\n");
      out.write("                </p>\n");
      out.write("\n");
      out.write("                <div class=\"btn_group\">\n");
      out.write("                  <button class=\"btn_01\">\n");
      out.write("                    <a href=\"#\">매니저 소개</a>\n");
      out.write("                  </button>\n");
      out.write("                  <button><a href=\"#\">상담하기</a></button>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <section class=\"area_5\">\n");
      out.write("        <h4>회원 인터뷰</h4>\n");
      out.write("        <p>성혼 커플의 러브스토리를 소개합니다.</p>\n");
      out.write("\n");
      out.write("        <div class=\"container_01\">\n");
      out.write("          <div class=\"inter_1\">\n");
      out.write("            <a href=\"#\"><img src=\"images/inter_img.svg\" alt=\"\" /></a>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"inter_2\">\n");
      out.write("            <li class=\"love_1\">\n");
      out.write("              <img src=\"images/love_01.png\" alt=\"\" />\n");
      out.write("            </li>\n");
      out.write("            <li class=\"love_2\">\n");
      out.write("              <img src=\"images/love_02.png\" alt=\"\" />\n");
      out.write("            </li>\n");
      out.write("            <li class=\"love_3\">\n");
      out.write("              <img src=\"images/love_03.png\" alt=\"\" />\n");
      out.write("            </li>\n");
      out.write("            <li class=\"love_4\">\n");
      out.write("              <img src=\"images/love_04.png\" alt=\"\" />\n");
      out.write("            </li>\n");
      out.write("            <li class=\"love_5\">\n");
      out.write("              <img src=\"images/love_05.png\" alt=\"\" />\n");
      out.write("            </li>\n");
      out.write("            <li class=\"love_6\">\n");
      out.write("              <img src=\"images/love_06.png\" alt=\"\" />\n");
      out.write("            </li>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <section class=\"area_6\">\n");
      out.write("        <h4>회원 현황</h4>\n");
      out.write("\n");
      out.write("        <p class=\"marriage\">\n");
      out.write("          <span>초혼 </span>\n");
      out.write("          <span>/ </span>\n");
      out.write("          <span>재혼</span>\n");
      out.write("        </p>\n");
      out.write("\n");
      out.write("        <div class=\"container_02\">\n");
      out.write("          <div class=\"current_1\">\n");
      out.write("            <div class=\"inner_01\">\n");
      out.write("              <p>남성회원의 연봉은?</p>\n");
      out.write("              <li>\n");
      out.write("                <img src=\"images/down_01.png\" />\n");
      out.write("              </li>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"inner_02\">\n");
      out.write("              <p>남녀 평균키는?</p>\n");
      out.write("              <li>\n");
      out.write("                <img src=\"images/down_02.png\" />\n");
      out.write("              </li>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"inner_03\">\n");
      out.write("              <p>여성회원 학력은?</p>\n");
      out.write("              <li>\n");
      out.write("                <img src=\"images/down_03.png\" />\n");
      out.write("              </li>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- 아래 footer 하단 고정 -->\n");
      out.write("    <footer class=\"footer\">\n");
      out.write("      <div class=\"footer-content\">\n");
      out.write("        <h3>(주)Re:connect</h3>\n");
      out.write("        <span>대표 : Recycle</span>\n");
      out.write("        <span>사업자등록번호 : 999-99-99999</span>\n");
      out.write("        <span\n");
      out.write("          >주소 : (34838)대전광역시 중구 중앙로121번길 20 (선화동 41) 2층</span\n");
      out.write("        >\n");
      out.write("        <span>Tel.042-222-2402</span>\n");
      out.write("        <ul class=\"footer-socials\">\n");
      out.write("          <li>\n");
      out.write("            <a href=\"#\"><img src=\"images/ico_image.svg\" alt=\"ico_image\" /></a>\n");
      out.write("            <!-- 임시로 로그아웃 넣어 놨음 -->\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"https://www.instagram.com/\"\n");
      out.write("              ><img src=\"images/ico_instagram.svg\" alt=\"ico_instagram\"\n");
      out.write("            /></a>\n");
      out.write("          </li>\n");
      out.write("          <li>\n");
      out.write("            <a href=\"https://www.youtube.com/\"\n");
      out.write("              ><img src=\"images/ico_youtube.svg\" alt=\"ico_youtube\"\n");
      out.write("            /></a>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"footer-menu\">\n");
      out.write("          <p>\n");
      out.write("            copyright &copy;2023 by\n");
      out.write("            <a href=\"index.jsp\">Re:connect.</a>\n");
      out.write("            All pictures cannot be copied without permission.\n");
      out.write("          </p>\n");
      out.write("          <ul class=\"f-menu\">\n");
      out.write("            <li><a href=\"html/index.jsp\">Home</a></li>\n");
      out.write("            <li><a href=\"html/dash.jsp\">About</a></li>\n");
      out.write("            <li><a href=\"html/estimate.jsp\">Contact</a></li>\n");
      out.write("            <li><a href=\"html/FAQ.jsp\">FAQ</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <script src=\"https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js\"></script>\n");
      out.write("    <script src=\"script/index.js\"></script>\n");
      out.write("    <script src=\"script/loginSession.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
